### ISSUE TITLE
Enhancement request - Split view when more than one screen

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentralRouter#15]
May I request please a Split Screen View? In order when client have a two screens and I also have two screens, it will be very useful to have that option.

Let say if we have this:
![90166783-a4ea3e80-dd92-11ea-84e1-53131e0fcacd](https://user-images.githubusercontent.com/59362521/99651764-f1f34600-2a4e-11eb-97d6-0f0832ddea1f.png)

and once it is selected to have two windows of Router Viewer, one windows for Screen 1, and the second one for screen 2.

If the picture below is achievable - that would be great:

![image](https://user-images.githubusercontent.com/59362521/99653355-cf622c80-2a50-11eb-8ea6-65ea3a7e5566.png) 

In this case on my local PC I will be able to move different remote screens onto different local screens.

Thanks.

**Comment by cookta2012** [comment]
I have been meaning to look into that

**Comment by cookta2012** [comment]
It would require a rewrite of some of the core components from what I can tell to do that because when I use the router and the website they both keep the same view, there is another possibility I will look at, BUT it would be conceivably be a hackaround.

@Ylianst can a screen be arbitrarily shown without changing the selected screen on the server side?

**Comment by vitko-bg** [comment]
That would be great if that is achievable.

**Comment by vitko-bg** [comment]
Is there any update on this? Thanks.

**Comment by cookta2012** [comment]
I've been going through computer problems. I might have it ironed out so I
might be able to start work on this again

**Comment by vitko-bg** [comment]
It has been fixed and now new option is working perfect, so closing the issue.
Thanks!
