### ISSUE TITLE
Request consent + Bar on Router Viewer

### ISSUE THREAD

**Issue by vitko-bg** [Ylianst/MeshCentralRouter#17]
May I request same options as in MC2 main webpage, to have them on MC Router when connecting via Router Viewer?

![image](https://user-images.githubusercontent.com/59362521/99910583-c4c0c500-2ce6-11eb-90fb-9566ad6df203.png)

I think the best way will be:
 - click on the agent and select "Remote Desktop..."

![image](https://user-images.githubusercontent.com/59362521/99910761-c474f980-2ce7-11eb-8cb0-c66ba5f2803a.png)

 - When remote desktop viewer is open NO automatic connection to be established and to have a right click on "Connect..." button

![image](https://user-images.githubusercontent.com/59362521/99910804-0140f080-2ce8-11eb-89e3-d4881a8a28ad.png)

 - With consent+bar, with consent only, bar only, and no consent at all

Please advise if that is possible and which way it will be better to have this option available.

**Comment by Ylianst** [comment]
Just published MeshCentral v0.7.7 with improved MeshCentral Router. Let me know if that works.

![image](https://user-images.githubusercontent.com/1319013/100552140-106cf480-323a-11eb-8576-71fb8894ed1a.png)

**Comment by vitko-bg** [comment]
Thanks!!!!!!!!!!!!!! Will update MC2 and MC Router and will let you know on the outcome!

**Comment by Ylianst** [comment]
Once you update the server, latest versions of MeshCentral Router will prompt for auto-update. Should make things easy.

**Comment by vitko-bg** [comment]
All work as requested!!! 
Thanks @Ylianst !!!!!!!!! You are the best!!!!!

Closing issue now, as it fixed :) 👍
