### ISSUE TITLE
Mappings only work for so long

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentralRouter#19]
So i have a bit on an issue with router (latest version and previous).

I use router to create remote mappings to enable me to access websites using router as a proxy.

It works lovely at first, but after a while (maybe 30 mins) it stops working, i can get to the homepage of the site I am mapped to, but any pages outside of the home page I get:

![image](https://user-images.githubusercontent.com/6532805/106146355-7c060c00-616e-11eb-88da-25b1d71f4c60.png)

Anyone else seeing the same ?

**Comment by drnikcuk** [comment]
@Ylianst are issues on router better reported on the meshcentral issue log or do you want them here ?

**Comment by easy124** [comment]
I'm having this same issue between a Windows 7 and 10 PC. Seems to happen twice a day
It's resolved by restarting the router program
The RoutePlus plugin does the same thing

**Comment by drnikcuk** [comment]
@easy124 I think its same issue, I use relays for winbox access and they stop working after a while also.

**Comment by vtacquet** [comment]
I am on MeshCentral Router for mac and it also stops working (same with the plugin RoutePlus https://github.com/ryanblenis/MeshCentral-RoutePlus)

**Comment by Ylianst** [comment]
Looking into this now.

**Comment by Ylianst** [comment]
Reading above, I don't know what I need to test. I am doing SSH and web page access and it seems to work file. Issues like it "stops working" are not helpful. I need much more details.

It seems like I need create a mapping and wait 30 minutes for it to fail? - Thanks.

**Comment by easy124** [comment]
The end-user claims there is no pattern for when ""got closed fragment"" happens and the port closes.
It happens sometimes frequent, sometimes less frequent. Sometimes in the middle of using it, sometimes not.
Drnikcuk, are you using Windows 7 or no?? It only happened with a Windows 7 PC involved for me. 

I will update if I find myself needing Windows 7 again

**Comment by Ylianst** [comment]
Ok. I may have found the problem. I renew authentication cookies every 24 minutes, but when creating a mapping, it takes the cookie at that time instead of using the latest one. So, eventually the mapping will has an old cookie and no new connections will happen unless you remove and re-create the mapping. I just fixed the code for this. Will be in MeshCentral Router v1.4.

**Comment by Ylianst** [comment]
FYI. MeshCentral Router v1.4 can be [downloaded here](https://info.meshcentral.com/downloads/MeshCentral2/MeshCentralRouter.exe).

**Comment by Ylianst** [comment]
Published MeshCentral v0.7.74 with latest MeshCentral Router or use link above with an existing server (no need to update the server). Let me know if that works.

**Comment by vtacquet** [comment]
> Published MeshCentral v0.7.74 with latest MeshCentral Router or use link above with an existing server (no need to update the server). Let me know if that works.

Hey @Ylianst is there a new mac version available too ? Thx

**Comment by drnikcuk** [comment]
Can confirm that in the windows version of the client the mappings are no longer lost after an extended period of time.

Thanks for the fix @Ylianst surprised more people hadn't spotted this one!
