### ISSUE TITLE
Update Tab order

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentralRouter#20]
Bit of a request here .... would it be possible to update the tab order that's used when setting up a new mapping?

Today this is how it works:

1. Right click host, then add map / relay map - this results in the cursor not been focused to any field (would be great if it was name)
2. Manually select the Name field, enter text and then hit tab - this then jumps the cursor to the cancel button (would be great if it went to the protocol selection)

And from there tab seems to jump from field to field .... it would be lovely if it followed the fields in the window.

Does that make any sense ?

**Comment by Ylianst** [comment]
Good request. Working on it now.

**Comment by Ylianst** [comment]
Just fixed all tab ordering for all dialog boxes. Will be in the next published version.

**Comment by Ylianst** [comment]
Published MeshCentral v0.7.74 with latest MeshCentral Router v1.4 with new tab ordering.

**Comment by drnikcuk** [comment]
Tab order is now correct, keyboard warrior OCD now extinguished. Thanks @Ylianst
