### ISSUE TITLE
Automatically reconnect when disconnected

### ISSUE THREAD

**Issue by cy11100** [Ylianst/MeshCentralRouter#24]
The current implementation of the MeshCentralRouter program seems to not include any auto-reconnect features, and if the connection breaks during an unattended session, the program logs you out and all connections are broken, requiring manual action to relogin and restore the saved connections.

This makes it difficult to keep a long-term connection open to another Meshcentral server, for example in SSH tunneling. Auto-reconnect should be implemented so that there is no need to reconnect every time the connection is disrupted.

**Comment by Ylianst** [comment]
Automatic reconnect was added a while back to MeshCentral Router. I will close this, but please open a new issue if something is not right.

![image](https://user-images.githubusercontent.com/1319013/176970847-f56fb5fb-ea74-4536-8ab0-f2b186f9d679.png)
