### ISSUE TITLE
Doubleclick action combobox is missing RDP item

### ISSUE THREAD

**Issue by omiT-84** [Ylianst/MeshCentralRouter#27]
I noticed when setting the doubleclick action to SSH, it opened RDP.

When I look in below file, I see the items added to the doubleclick combobox in the device settings:
https://github.com/Ylianst/MeshCentralRouter/blob/b17045a4577c2cff6136f41d2f81379751077828/DeviceSettingsForm.resx#L174

Item 6 should be RDP and SSH and SCP should be item 7 and 8 according to setDoubleClickDeviceAction on mainform.
https://github.com/Ylianst/MeshCentralRouter/blob/b17045a4577c2cff6136f41d2f81379751077828/MainForm.cs#L287

**Comment by vitko-bg** [comment]
Same here. Please fix it. Thanks

**Comment by omiT-84** [comment]
Thanks for reminding me about this,
I think I just made the fix, but have not tried it yet.
Will try to find some time this month to test and create a pull request for this.
