### ISSUE TITLE
Session disconnects after 300 - 317 seconds

### ISSUE THREAD

**Issue by dernippel** [Ylianst/MeshCentralRouter#4]
When opening a RDP oder SSH Session in MeshCentralRouter it disconnects automatically between after 300 to 317 seconds.
I observed this during a longer RDP-session (like a few hours) and this disconnects are very stable (mostly all 316/317 seconds). This is also discoverable on clients in different home networks.

MyEvents is showing the following: (IPv4 and IPv6 adresses are hidden)
![image](https://user-images.githubusercontent.com/1632500/80838452-58229380-8bf9-11ea-822f-9811ef5e9f69.png)

RDP is reconnecting automatically causing a black "waiting for recconection" screen for a few seconds. The SSH session (via putty) is terminated permanently.

I'm currently using meshcentral behind a apache reverse proxy. I did a test without the reverse proxy as well by changing my complete setup and have the same behavoir. So I would except the reverse proxy.

It looks like any kind of timeout.

I'm currently running meshcentral 0.5.11 (stable) with MeshCentralRouter 1.0.7416.
I can confirm this bug with meshcentral 0.5.18 and 0.5.19 with MeshCentralCouter 1.0.7416 as well.

In 0.5.19 the Router Version changed to a newer one wich even doesn't want to connect to meshcentral. I guess this might be another bug.

**Comment by Ylianst** [comment]
Does the disconnect only happen when there is no traffic on the correction?

**Comment by dernippel** [comment]
Yes, this happens on an active rdp session when working in it so there is traffic. The windows rpd client has an option to reconnect automatically (default is on), so there is a black screen for a few seconds showing something like "reconnecting...". 

Am 15. Mai 2020 22:21:44 MESZ schrieb Ylian Saint-Hilaire <notifications@github.com>:

**Comment by Ylianst** [comment]
Does this problem still occur? I may have fixed this a while back.

**Comment by Ylianst** [comment]
This is likely fixed. Please re-open if needed.

**Comment by dernippel** [comment]
I checked and it's working. Thank you.

**Comment by meichthys** [comment]
I'm seeing the 3 minute (or so) timeout disconnect on the MacOS Router
v0.0.4
