### ISSUE TITLE
"Unable to Connect" Error

### ISSUE THREAD

**Issue by frakman1** [Ylianst/MeshCentralRouter#42]
When running on a device behind a company firewall, I get the error "Unable to Connect"
Everything else works  however. I was able to install the agent and otherwise remotely control the device in every other way through the website (Remote Desktop, Files etc)
Something about the way that the MeshCentralRouter tool connects to the server must be on a non standard port that is getting blocked. 
Is there any chance that this traffic can use whatever traffic/ports that the mesh agent is already using successfully?
If not, can you please enumerate the ports that need to be opened for a firewall exception policy (unlikely to be approved but worth noting)

![image](https://user-images.githubusercontent.com/5826484/160249747-a747a864-19ec-4ec9-81ba-8bf2a909478b.png)

**Comment by wizdude** [comment]
you've entered the server name incorrectly. there should be no "https://" in front of it. it should just be the name of the server, ie: meshcentral.com or mesh.mydomain.com or whatever.
