### ISSUE TITLE
wont show single devices only groups

### ISSUE THREAD

**Issue by si458** [Ylianst/MeshCentralRouter#46]
when assigning a single device in meshcentral, the app is showing a blank screen and no devices

issue started here - https://github.com/Ylianst/MeshCentral/issues/4188

`ListViewGroup grp = devicesListView.Groups.Add(devicesListView.Groups.Count.ToString(), node.mesh.name);`
this is the line its crashing at it would seem, because we arent sending any groups, only the devices

EDIT: if you send the group with `NO RIGHTS` it will not crash, HOWEVER it shows ALL devices

**Comment by Ylianst** [comment]
Just put in a fix for this, will be in MeshCentral v1.0.45.

**Comment by si458** [comment]
yep all fixed with 1.0.45! closing

**Comment by githubbiswb** [comment]
Confirmed, thank you everyone for all of the hard work done here!
