### ISSUE TITLE
MeshCentralRouter closes after entering 2-factor token

### ISSUE THREAD

**Issue by bsmout** [Ylianst/MeshCentralRouter#5]
The application closes without showing any error. From the windows application log:

Toepassing: MeshCentralRouter.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.NullReferenceException
   bij MeshCentralRouter.MeshCentralServer.processServerData(System.String)
   bij MeshCentralRouter.MeshCentralServer+xwebclient.ProcessWsBuffer(Byte[], Int32, Int32, Int32)
   bij MeshCentralRouter.MeshCentralServer+xwebclient.ProcessBuffer(Byte[], Int32, Int32)
   bij MeshCentralRouter.MeshCentralServer+xwebclient.OnTlsDataSink(System.IAsyncResult)
   bij System.Net.LazyAsyncResult.Complete(IntPtr)
   bij System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   bij System.Net.Security._SslStream.ProcessFrameBody(Int32, Byte[], Int32, Int32, System.Net.AsyncProtocolRequest)
   bij System.Net.Security._SslStream.ReadHeaderCallback(System.Net.AsyncProtocolRequest)
   bij System.Net.AsyncProtocolRequest.CompleteRequest(Int32)
   bij System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32)
   bij System.Net.FixedSizeReader.ReadCallback(System.IAsyncResult)
   bij System.Net.LazyAsyncResult.Complete(IntPtr)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bij System.Net.ContextAwareResult.Complete(IntPtr)
   bij System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   bij System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   bij System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by dernippel** [comment]
I have the same behaviour. Started the router with the "-debug" command line argument the debug.log shows this:

Connect-wss://sub.domain.de/control.ashx
Debug-Websocket TCP connected, doing TLS...
Debug-Websocket TLS setup, sending HTTP header...
Debug-Websocket got setup upgrade header.
Debug-Websocket got data.
ServerData-{"action":"close","cause":"noauth","msg":"tokenrequired","email2fa":false,"sms2fa":false}
Debug-Websocket got closed fragment.
Connect-wss://sub.domain.de/control.ashx
Debug-Websocket TCP connected, doing TLS...
Debug-Websocket TLS setup, sending HTTP header...
Debug-Websocket got setup upgrade header.
Debug-Websocket got data.
ServerData-{"action":"close","cause":"noauth","msg":"tokenrequired","email2fa":false,"sms2fa":false}
Debug-Websocket got closed fragment.

I'm using the two factor authentication via authenticator app.

**Comment by Fred1984** [comment]
hello i have the same problem , but I'm not using the 2 factors authentication, just after click on connect the windows close without any error messages. i tried on another test machine with a fresh install of meshcentral and they do both the same.

i'm running on 0.5.49 will try to update to 0.5.50.
@Ylianst can you please have a look on this topic?

Best regards
Frederici

**Comment by Ylianst** [comment]
Apologies for the delay. Is this still a problem? I think it's been fixed and I never closed this issue.

**Comment by bsmout** [comment]
It's fixed. Thanks for the follow up.

**Comment by Ylianst** [comment]
Sorry about that. I am working on a bunch of improvements to MeshCentral Router, should be out later today.
