### ISSUE TITLE
MC Router not display my devices since updated the server in version 1.1.13

### ISSUE THREAD

**Issue by alyatis85** [Ylianst/MeshCentralRouter#62]
**Describe the bug**
I can log normaly with the mc router client, but once logged in, i can't see my devices.
No error appears

**Screenshots**
![image](https://github.com/Ylianst/MeshCentralRouter/assets/7759710/afa0bc98-493e-46e5-88ad-b5f2a9f3af01)

**Server Software (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Google Cloud
 - Network: WAN
 - Version: 1.1.13
 - Node: 10.19.0

**Remote Device (please complete the following information):**
 - Device: Desktop
 - OS: Ubuntu
 - Version: 22.10
 
**Additional context**
Meshcentral router version : 1.8.7998

**Comment by alyatis85** [comment]
I don't use cloudflare.
Yes the version of node is old but it was perfectly working with MC 1.1.10 before upgrading to 1.1.13
Same problem with router 1.8.8680 : Login OK but I can't see my devices

**Comment by si458** [comment]
Is ur user as admin with full access? Or is it limited access?
Do u access only certain group?
Certain devices?
What's the list like in your Web ui?

**Comment by alyatis85** [comment]
I'logged in meshcentral router with my superadmin fullrigths.
No groups, No devices availables
It's fully working well in the web UI

**Comment by alyatis85** [comment]
I just upgraded NODE JS to tthe latest version v20.8.1
WEB UI is working well
but same problem with MC Router on Ubuntu.

**Comment by alyatis85** [comment]
MC Router not display my devices since updated the server in version 1.1.13
I can see all my users properly in MC web console, but not from the router under Ubuntu. 
The same version of the router works on Windows.

I don't understand as it was working well before updating the server . 

Any idea ?

**Comment by si458** [comment]
@alyatis85 how did you install meshcentralrouter on ubuntu?
all i can find is windows exe ? 
i cant find any linux versions of meshcentralrouter?

**Comment by alyatis85** [comment]
Hi,

Unfortunetely it still not working after upgrading my Ubuntu from 22.10 to 23.04 + full upgrade packages + test under XFCE desktop ... 
I also have removed/purged/reinstalled mono and wine package (i also confirm that i try to connect using the .exe windows binary version  1.8.86.80)
Anyway the show list does dot work : i cant see any machine
The same exe work like a charm with Windows 7, 10, 11 ! (tested on both of them)

Please help. What can we do more ?

**Comment by si458** [comment]
im not 100% sure as i just cant replicate your issue?

the only issue i have with wine is i get `certificate is not trusted` in the router, which i then click `ignore` and it just carries on
(even tho i have a lets encrypt cert which is valid everywhere?)

whats the output of `wine --version` ?

**Comment by alyatis85** [comment]
$ wine --version
**wine-8.0.1**

**Comment by si458** [comment]
whats the output if you browse to the folder where the exe is in terminal
then `wine MeshCentralRouter.exe` then try logging in?

**Comment by alyatis85** [comment]
~/Téléchargements$ wine MeshCentralRouter.exe

**The console give :** 
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
00d4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00d4:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 00000000008FE1F0, 0000000000A377D0, 00000000008FE1F8, 00000000008FE1E8
00d4:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 00000000008FE1F0, 0000000000A377D0, 00000000008FE1F8, 00000000008FE1E8
00d4:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 00000000008FE1F0, 0000000000A377D0, 00000000008FE1F8, 00000000008FE1E8
00d4:fixme:font:get_nearest_charset TCI failing on 20000000
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 20000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-gujr-extra\\aakar-medium.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-beng-extra\\Ani.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\malayalam\\Dyuthi-Regular.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\Gargi\\Gargi.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\Gubbi\\Gubbi.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-deva-extra\\kalimati.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\Navilu\\Navilu.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-telu-extra\\Pothana2000.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-gujr-extra\\Rekha.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-deva-extra\\samanata.ttf"
00d4:fixme:font:find_matching_face Untranslated charset 255
00d4:fixme:font:get_nearest_charset returning DEFAULT_CHARSET face->fs.fsCsb[0] = 00000000 file = L"\\??\\Z:\\usr\\share\\fonts\\truetype\\fonts-telu-extra\\vemana2000.ttf"
00d4:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 0, lp 0
006c:fixme:imm:ImeSetActiveContext (0000000000010026, 0): stub
006c:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000010026): stub
00d4:fixme:imm:ImeSetActiveContext (0000000000010052, 1): stub
00d4:fixme:imm:ImmReleaseContext (000000000001007A, 0000000000010052): stub

**Comment by alyatis85** [comment]
And the MeshCentralRouter window Open normally. I log into the application and then again, empty machine list

**Also the following line appeared in the console once logged in :** 
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented
0058:fixme:nsi:ipv6_forward_enumerate_all not implemented

**Comment by si458** [comment]
i see the below show up after the `ipv6_forward_enumerate_all` messages, weird?
```
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 10a1, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 0, lp 2819668
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 1, lp 28196f8
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 10a1, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 0, lp 2a7a308
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 2, lp 2a7a398
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 10a1, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 109d, wp 1, lp 0
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 0, lp 2a7bff8
01dc:err:listview:LISTVIEW_WindowProc unknown msg 1091, wp 3, lp 2a7c088
```

**Comment by si458** [comment]
@alyatis85 can you try my steps above with a docker image of a fresh install of ubuntu 22.04 and see if you can connect from inside that?
if you can then its something with your setup of ubuntu
if you cant then its something with the setup of your meshcentral

the only other thing you can try from what i have found other say is
stop meshcentral
`npm install meshcentral` to install latest version again
`npm audit fix` this tried to fix any issues
start meshcentral
try again?

**Comment by alyatis85** [comment]
@si458 : Hi,
I tried your method and it still not working on Ubuntu fresh install.
It's working with the windows version.
I'm a little bit confused as everything was working well before upgrading the server.

**Comment by si458** [comment]
what about updating to 1.1.15 ? (take shapshot before hand if needs be)

**Comment by alyatis85** [comment]
Already done. Nothing has changed.
is there any debug mode on client mc router side ?

**Comment by alyatis85** [comment]
Hello all,
Just to feedback that i found a workaround by installing .Net 4.8 for Wine using Winetricks and it works : i can see my list of machine again.
I don't know whare are the pre-requisites to run MeshcentralRouter on Linux but if that can be documented or recommanded somewhere it could be usefull.

Regards,

**Comment by si458** [comment]
@alyatis85 glad u got it sorted!
but whats weird is i created a fresh ubuntu 22.04 vm and installed wine 8 as you have above and didnt need to install .net 4.8 ?
i even tried it in a docker contaer as explained above - https://github.com/Ylianst/MeshCentralRouter/issues/62#issuecomment-1785004259
so not sure WHY your setup needed .net 4.8?
maybe you are using Win7 as the Wine version and mine is Win10? who knows!?

**Comment by alyatis85** [comment]
I just said it was a workaround, not the right solution. Both Win7 and Win 10 are working with .Net 4.8.
But without that component, it's not working. Is @Ylianst  could confirm there is or not some component dependencies with .NET ? and wich version ?
