### ISSUE TITLE
WebRTC support for MeshCentral Router

### ISSUE THREAD

**Issue by maccn** [Ylianst/MeshCentralRouter#66]
MeshCentral Router is great tool and with its increasing usage, more and more traffic will be relayed via MeshCentral Server and increase the server's bandwidth usage and hosting cost.

Just to see if you will consider to make MeshCentral Router to support WebRTC, which can make the MeshCentral Router will try to establish connection with MeshCentral Agent directly first to reduce the server's relay pressure? 

I assume that both MeshCentral Router and MeshCentral Agent use your own WebRTC stack and doesn't depend on Chrome or Firefox's WebRTC, which has less WebRTC compatibility issue when transferring P2P data between MeshCentral Router and Againt via WebRTC..

BTW, where can I find the source code of MeshCentral Router? I tried to find in MeshCentral Server and MeshCentral Agent's source code, but no luck. Thanks in advance for the help.

**Comment by si458** [comment]
closing in favor of #2
