### ISSUE TITLE
MeshCentral Router remember logon for 30 days (2FA)

### ISSUE THREAD

**Issue by drnikcuk** [Ylianst/MeshCentralRouter#69]
I haven't found a way to do this so assume it's not available, but it would be great if there was an option for the meshcentral router client to remember a device for 30 days so that 2fa is not required for every login (like the web logon option)

Of course, this not been an option could be deliberate?

**Comment by si458** [comment]
this has been implemented and a tiny fix has also been included to fix the 2fa freezing at times
