### ISSUE TITLE
Enhancement Request: Naming Port Mapping

### ISSUE THREAD

**Issue by cookta2012** [Ylianst/MeshCentralRouter#7]
Hey Ylianst, 
I just want to first say amazing job. Working for Intel and managing a ambitious and well working project such as this KUDOS!

I had one relatively small request is is possible to add a way in the mappings section to give a mapping a "Friendly Name"
I would do it but I really don't have any development software installed ATM, using shared computer >:|

Thanks for reading this have a good one and stay safe.

**Comment by cookta2012** [comment]
I took the time and downloaded Visual Studio and implemented my idea.
#8 is the pull if you want to pull it in
I hereby relinquish all rights to any code provided herein.

**Comment by cookta2012** [comment]
Pictures are in the PR

**Comment by Ylianst** [comment]
Thanks for the PR. It's accepted. Sorry for the delay. Making more changes and fixes to MeshCentral Router and will be releasing it with MeshCentral v0.6.39.

**Comment by Ylianst** [comment]
Published MeshCentral v0.6.39 with your improvement. Thanks.
