### ISSUE TITLE
Meshcentral Router hanging with 2FA

### ISSUE THREAD

**Issue by Taapo** [Ylianst/MeshCentralRouter#71]
Using the win32 version of the router, when I have 2FA enabled, it hangs upon startup (had it working once after restarting computer, but not when trying a second time).

When I disable 2FA in meshcentral, all is good and works flawlessly.

**Comment by philerb** [comment]
> Hi all, just wanted to update i think ive fixed the issue, for some reason when the app calls the `twoFactorCookie` action (because you ticked the save token for x days), it appears to just HANG because the `SendFragment` in `websocketclient.cs` of meshcentralrouter seems to try locking something? and for some reason its hanging when it tries to lock, so a simply fix is to just delay running that command for 2 and a half seconds, then it works no problem! no crashing! if you want to try my build its attached here with the fix from the PR attached make sure to click ignore or NOT update when it probs for a different version [MeshCentralRouter.zip](https://github.com/Ylianst/MeshCentral/files/14103440/MeshCentralRouter.zip)

Confirmed that this version (v1.8.8795.35235) works for me when checking the option to not ask for MFA for 30 days. Thanks!!

**Comment by si458** [comment]
glad it works @philerb!
i have no idea if the version number is the same as what you download from the web ui? can u tell me at all?
i just learnt a little C lang, found the line causing the bug, recompiled it with the timer fix, and then uploaded it for other to try!

**Comment by philerb** [comment]
v1.8.8795.35235 is what you provided in the ZIP file above. That works for me.

I'm on v1.1.20 of MeshCentral and the version of Router available in my web ui is 1.8.8680.22189, which does not work with remembering MFA. But using your version of Router does work.

**Comment by si458** [comment]
@philerb great thank you!
im guessing visual studio 2022 is increasing the version number every time i recompiled the exe haha!

**Comment by smartekIT** [comment]
> Hi all, just wanted to update i think ive fixed the issue, for some reason when the app calls the `twoFactorCookie` action (because you ticked the save token for x days), it appears to just HANG because the `SendFragment` in `websocketclient.cs` of meshcentralrouter seems to try locking something? and for some reason its hanging when it tries to lock, so a simply fix is to just delay running that command for 2 and a half seconds, then it works no problem! no crashing! if you want to try my build its attached here with the fix from the PR attached make sure to click ignore or NOT update when it probs for a different version [MeshCentralRouter.zip](https://github.com/Ylianst/MeshCentral/files/14103440/MeshCentralRouter.zip)

Well my workaround to this long time ago, was logging to the webUI in the browser, then in the browser console (F12) look for the cookies value of "twoFactorCookie"
then add that as a key in the windows registry in the router windows registry node. this way it doesn't even prompt for 2FA because the cookie value i copied from the browser was already set to not expire for the next 30 days.
I know it was an ugly workaround and hope yours would fix this issue permanently.

**Comment by si458** [comment]
@smartekIT good idea! Never thought of that!
