### ISSUE TITLE
remote desktop connect to rdp sessions like web ui

### ISSUE THREAD

**Issue by OutbackMatt** [Ylianst/MeshCentralRouter#80]
**Describe the bug**
In MeshCentral Router, in [Devices] tab
Right click and a number of options are available

Choosing 'Remote Desktop...', then 'Privacy Bar' only opens a console session, but does it really quickly
Choosing 'RDP' opens a RDP session, but often doesn't connect (seems to skip every second attempt)

I never realised that these right click options were available until today.
Using the [Mappings] tab, it seems that the RDP type session is used

users like the 'privacy bar' with the connect / disconnect buttons, and the speed with which it opens,  but we really need to be able to have multiple connections to a single RDP server please, and conversely, a quick and direct console connection would be great from the main meshcentral web portal

**To Reproduce**
From MeshRouter, right click any machine
**Screenshots**
<img width="263" alt="image" src="https://user-images.githubusercontent.com/7231493/181422467-821473ae-a02f-4c06-bc0a-09d6477e1196.png">

**Expected behavior**
Quick connections no matter which method choosen

**Server Software (please complete the following information):**
 - Server OS: - Ubuntu 20.04  
 - Virtualization: Installed as a HyperV VM
 - Network: WAN
 - Version: [1.0.60]
 - Node: [18.6.0]
 - Browser: [Google Chrome]

**Remote Device (please complete the following information):**
 - Device: [Windows Server 2012 R2 Standard with Demote Desktop enabled]
 - Version: [9600]
 - Current Core Version (if known): [181657594]

**Comment by si458** [comment]
just clarifing this issue,
the issue is when you click 'Remote Desktop' it connects to the console session (the desktop/monitor)
but if remote devices have multiple rdp sessions, you cannot connect to them,
you would like the ability to connect to them

**Comment by si458** [comment]
ignore last comment closing as stale and my clarifing was incorrect
