### ISSUE TITLE
MeshRouter not connecting

### ISSUE THREAD

**Issue by rowds15** [Ylianst/MeshCentralRouter#89]
Hi Not sure if it's just me, but I'm unable to get MeshCentralRouter to connect.
I'm just getting Unable to Connect on MeshCentralRouter. I don't know what logs I need to look at.

Tested on 2 different computer with 2 different Administrator Accounts

Running Version 1.0.23 no plugins

**Comment by si458** [comment]
plz download the latest version from https://meshcentral.com/downloads.html
or
download it from meshcentral 1.1.24
and try again and re-open if issue still persists
