### ISSUE TITLE
Special key combinations don't work in remote desktop

### ISSUE THREAD

**Issue by cookta2012** [Ylianst/MeshCentralRouter#9]
Yes I downloaded and built the newest code last night for the router. I also updated the agent, and meshcentral2 server to the latest public release.
Examples include:
Win + R
Shift + Del (while a file is selected)

**Comment by cookta2012** [comment]
I don't know how you would want to handle canceling the Win key when the application has focus, ex. the inclusion of a secondary library or if you would rather use a Windows native keyboard hook to accomplish this task.

**Comment by cookta2012** [comment]
through more testing i found the windows key combinations are working but do not send the Win up event when it is interrupted by the start menu and or run box on the host machine.

**Comment by cookta2012** [comment]
When I use Win+R it sticks the win key down on the agent until I press the win key a time or two on its own

**Comment by Ylianst** [comment]
The "Windows" key clearly does not work. I get notified when the key goes does but not when it goes up and it's processed by both local and send remotely. I am going to remove the window key support for now. I will need to build an alternative.

**Comment by cookta2012** [comment]
I have been able to get it to come up. but i have to spam it a couple of
times on the viewer. And I understand. I will have some mockups later.

**Comment by Ylianst** [comment]
I just published a new version of MeshCentral Router, but right now the Window key does not work anymore. I will need to fix this. If you have ideas, that would be appreciated.

**Comment by cookta2012** [comment]
I will find out in the morning. Would you be opposed to including 3rd party
libraries?

**Comment by Ylianst** [comment]
All depends on the license. Obviously, some 3rd party libraries can't be included in an Open Source project.

**Comment by cookta2012** [comment]
So far I have worked up a very crude keyboard hook, im working on flushing it out

**Comment by cookta2012** [comment]
I got it working the way I had intended. So now all that is needed is testing. I had the idea where you could be controlling multiple computers at once and you click a button and you can type on all of them at once. that is how it is currently implemented. What i mean is. It is implemented in a way that function would be trivial to implement.

**Comment by cookta2012** [comment]
https://github.com/cookta2012/MeshCentralRouter/tree/develop
if there are any problems let me know. I know i have to rebase still.

**Comment by cookta2012** [comment]
PR #12

**Comment by cookta2012** [comment]
Next thing I'm adding is a checkbox for auto clipboard sync

**Comment by cookta2012** [comment]
Please hold on merging due to, further debugging
