### ISSUE TITLE
Feature Request: MeshCentral Router Applications Edit option

### ISSUE THREAD

**Issue by b8two** [Ylianst/MeshCentralRouter#90]
Hi,

I had associated the SSH putty to Terra term, the program would launch but it wouldn't take the parameters correctly.
However trying to fix this had no GUI option in MeshCentral Router.

I found the registry entry location to fix the path, it would be good to have an edit function in MeshCentral Router.
`HKEY_CURRENT_USER\SOFTWARE\OpenSource\MeshRouter`

This would tie in nicely with Ylianst/MeshCentral#3964

**Comment by si458** [comment]
plz download the latest version from https://meshcentral.com/downloads.html
or
download it from meshcentral 1.1.24
and try again and re-open if issue still persists
