### ISSUE TITLE
MeshCentral Router is getting hang

### ISSUE THREAD

**Issue by kuksabong** [Ylianst/MeshCentralRouter#91]
Hi. Ylian!
When connecting to the remote desktop, MeshCentral Router is getting hangs as shown below.

![그림1](https://user-images.githubusercontent.com/6889244/126110713-592860e5-5c46-452f-8bf4-79e0992bdef9.png)

I just upgraded the MeshCentral Router version to the **latest version(v1.8.7867)** and then tested again, but it didn't solve the problem.

 - Current MeshCentral version             : **v0.8.80**
 - Current MeshCentral Router Version : **v1.8.7867**

After testing several versions of the MeshCentral router, I found that this issue started to occur with the **MeshCentral router version v1.8.7853**.

##############################################################################
@@ Test Result @@
o For MeshCentral Router **v1.8.7853 ~ v1.8.7867** 
The remote desktop on the web site works fine.
The remote desktop in MeshCentral Router works fine on Windows 10 Pro - 2004 [OS build 19041]
The remote desktop in MeshCentral Router does not work on Windows 10 Pro - 21H1 [OS build 19043]
The remote desktop in MeshCentral Router does not work on Windows 7 Pro v6.1

o For MeshCentral Router **v1.7.7846**
In MC Router **v1.7.7.846**, the remote desktop works fine regardless of the Windows 10 version.
##############################################################################

**Comment by si458** [comment]
plz download the latest version from https://meshcentral.com/downloads.html
or
download it from meshcentral 1.1.24
and try again and re-open if issue still persists
