### ISSUE TITLE
Add the chat window option / button to the remote desktop

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [Ylianst/MeshCentralRouter#97]
Hello,
This isn't an issue, rather a suggestion / feature request.
I'm a big fan of the Remote Desktop option within the MeshCentralRouter.
I like the full screen and it has the Remote Files.
The one feature that is missing is Chat.
It would be great if the Chat button / option could be added.
Thanks

**Comment by si458** [comment]
Would a simple chat button suffice?

Click it, open up button on remote client and also opens up ur browser?

Do u want the button inside the remote desktop screen?

What about a right click option in the device list?

**Comment by ZENAdmin-Ops** [comment]
I think the same or very similar function to the chat button within the Mesh Central 'console' / portal.

I was thinking another button - next to 'Remote Files' which says 'Chat'

A right-click option in the device list would be good as well. 

I guess ideally have both, but if one is a lot easier to implement than the other. Then go with the easy option.

**Comment by si458** [comment]
No that's perfectly fine!

I'm sure it's straight forward!

Will have a look Monday for you!

**Comment by si458** [comment]
ok please can you give this exe a try?
when it asks to update the exe JUST SAY NO (otherwise it will redownload the version from your meshcentral setup)
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16494457/MeshCentralRouter.zip)

**Comment by ZENAdmin-Ops** [comment]
I my side it’s not working.

I think the URL is wrong.

***@***.***$zs1s$vVpBVcAfw8ZW54SULORWTMmnSqm51fJYSE=

I’m using port 5443

Regards,
Vaughan

**Comment by si458** [comment]
ah! port number! can you just share your config.json? (hide secrets hehe)

**Comment by ZENAdmin-Ops** [comment]
Regards,
Vaughan

**Comment by si458** [comment]
give this version a shot 
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16494991/MeshCentralRouter.zip)

**Comment by ZENAdmin-Ops** [comment]
That works

**Comment by ZENAdmin-Ops** [comment]
That means a chat message can be sent before connecting.

**Comment by si458** [comment]
i will look into that for you, as the right click is built automatically so not straight forward!

**Comment by si458** [comment]
give this a shot!  https://github.com/Ylianst/MeshCentralRouter/commit/38580b4d0c802a51f9731f4edcca7e0f5fda287f
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16508756/MeshCentralRouter.zip)

**Comment by ZENAdmin-Ops** [comment]
That's perfect!

**Comment by si458** [comment]
glad its sorted and working! BTW thank you for your donation ❤️ 💷
