### ISSUE TITLE
Bug in file transfer. File transfer completes without error, but transferred file is corrupt

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [Ylianst/MeshCentralRouter#99]
**Describe the bug**
Bug in file transfer. File transfer completes without error, but transferred file is corrupt

**To Reproduce**
1. Using MeshCentral Router. Remote Desktop to Windows 11 client
2. Click on Remote Files
3. Select source file (in this case an MSI) and destination folder
4. Transfer the MSI
5. Run the MSI, eventually crashes with error (refer to screenshot)
6. Tried twice using MeshCentral
7. Transferred the same file using TeamViewer and MSI installed without issue.

**Expected behavior**
Transferred file to execute on the destination without error.

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Windows 10 Pro
 - Virtualization: Hyper-V VM
 - Network: WANonly
 - Version: 1.1.24
 - Node: 20.15.0

**Client Device (please complete the following information):**
 - Device: Latitude 7410
 - OS: Windows 10 Pro
 - Network: Remote over WAN
 - Browser: N/A
 - MeshCentralRouter Version: 1.8.8984.19829

**Remote Device (please complete the following information):**
 - Device: OptiPlex 7070
 - OS: Windows 11 Pro
 - Network: Remote over WAN
 - Current Core Version (if known): [**HINT**: Go to a device then `console` Tab then type `info`]

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
  "__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "mc1.zen.net.au",
    "WANonly": true,
	"_LANonly": true,
    "sessionKey": "secret",
    "_port": 443,
    "aliasPort": 5443,
	"MpsAliasPort": 54433,
    "_redirPort": 80,
    "_redirAliasPort": 80,	
	"mongodb": "mongodb://127.0.0.1:27017/meshcentral",
    "mongodbcol": "meshcentral",
	"autoBackup": {
	"mongoDumpPath": "C:/Program Files/MongoDB/Server/7.0/bin/mongodump.exe",
	"backupIntervalHours": 24,
	"keepLastDaysBackup": 10,
	"zipPassword": "secret",
	"backupPath": "C:/MeshCentral/meshcentral-backups",
	"maxFiles": 10
	}
  },
  "domains": {
    "": {
      "_title": "MyServer",
      "_title2": "Servername",
      "_minify": true,
      "_newAccounts": true,
      "_userNameIsEmail": true
    }
  },
  "_letsencrypt": {
    "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before trying Let's Encrypt.",
    "email": "info@zen.net.au",
    "names": "mc1.zen.net.au",
    "skipChallengeVerification": true,
    "production": false
  }
}
```
<img width="515" alt="Error_executing_MSI_after_using_MeshCentral_file_transfer" src="https://github.com/user-attachments/assets/573c89fb-a31e-4019-a948-003141916d4f">

**Comment by si458** [comment]
Yes this happens from time to time according to others, but im not sure why? 
Will have to look into it abit more
What sorta size is the msi?

**Comment by ZENAdmin-Ops** [comment]
97MB

**Comment by si458** [comment]
Strange one have u checked the hash of the file on ur local PC then the hash of the file on the remote pc?
Do they match?

**Comment by si458** [comment]
That's fine, I wanted you to just verify if the file hash on ur local computer matches/doesn't match the remote file!

I have a feeling it won't match so need to look into why!

I do remember seeing an issue somewhere that said something about the file transfer was adding like 2 extra bytes to the end of the file? Will have to have a look during the week!

**Comment by ZENAdmin-Ops** [comment]
Tomorrow I'll do some analysis to try and identify the differences

**Comment by ZENAdmin-Ops** [comment]
I've done a binary compare of the two files.

The differences look to be significant, although I'm not familiar with the utility.
<img width="597" alt="MC_BinaryCompare_MSI_files_46_differences" src="https://github.com/user-attachments/assets/be7e21db-5976-4b8a-8d58-fd2c76292b51">
<img width="594" alt="2nd_difference_MC_BinaryCompare_MSI_files_46_differences" src="https://github.com/user-attachments/assets/d889ff0b-9feb-406b-a83b-87578c3643fd">

**Comment by ZENAdmin-Ops** [comment]
BTW when I use <tab> in a command prompt using the MC Router RDP, the tab key brings up a list of windows to switch between.

Rather than auto-completing the current entry in the cmd window.

Can I turn-off the switch between windows thing?

**Comment by ZENAdmin-Ops** [comment]
I ended up using the file compare (FC) cmd.

There are a lot of differences
[fc.txt](https://github.com/user-attachments/files/16758791/fc.txt)

**Comment by si458** [comment]
@ZENAdmin-Ops ok will have a look when i get chance

**Comment by ZENAdmin-Ops** [comment]
I tested twice.

It's painfully slow. But both times the file transferred OK.

**Comment by si458** [comment]
when you have minute please try this exe 
[MeshCentralRouter.zip](https://github.com/user-attachments/files/16767497/MeshCentralRouter.zip)
includes a few fixes from here https://github.com/Ylianst/MeshCentralRouter/commit/f24b120f5b0e1ec7c656c54e3afe82703e7020f0

**Comment by ZENAdmin-Ops** [comment]
That's perfect.

I tested a few times and worked each time.

Thanks!

**Comment by si458** [comment]
@ZENAdmin-Ops glad it's sorted!
I have a feeling that because it was transferring small bytes at a time, it was messing things up?
So simply increasing the size of bytes it sends to the same as the web ui and meshctrl.js, it seemed to do the trick!
